### ISSUE TITLE
Getting an error each time I want to open any file

### ISSUE THREAD

**Issue by Quantfoam** [pyplotter/pyplotter#2] opened 2023-07-25 12:07 UTC
Hi, your software look really nice and I am just trying to use it for the first time. When I want to open any file (a basic Qcodes db file or a csv) I get the following errors

```
File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\sources\main.py", line 347, in loadedDataFull
    self.addPlot(plotRef        = plotRef,
  File "\pyplotter\pyplotter\sources\main.py", line 482, in addPlot
    p = WidgetPlot1d(x                  = data[0],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\pyplotter\pyplotter\sources\widgetPlot1d.py", line 281, in __init__
    self.resize(*self.config['dialogWindowSize'])
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'float'
  resize(self, w: int, h: int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "\pyplotter\pyplotter\sources\main.py", line 347, in loadedDataFull
    self.addPlot(plotRef        = plotRef,
  File "\pyplotter\pyplotter\sources\main.py", line 482, in addPlot
    p = WidgetPlot1d(x                  = data[0],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\pyplotter\pyplotter\sources\widgetPlot1d.py", line 281, in __init__
    self.resize(*self.config['dialogWindowSize'])
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'float'
  resize(self, w: int, h: int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "\pyplotter\pyplotter\sources\main.py", line 347, in loadedDataFull
    self.addPlot(plotRef        = plotRef,
  File "\pyplotter\pyplotter\sources\main.py", line 482, in addPlot
    p = WidgetPlot1d(x                  = data[0],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\pyplotter\pyplotter\sources\widgetPlot1d.py", line 281, in __init__
    self.resize(*self.config['dialogWindowSize'])
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'float'
  resize(self, w: int, h: int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\ui\statusBar.py", line 208, in updateProgressBar
    progressBar.setValue(int(val*progressBar.decimal))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
Traceback (most recent call last):
  File "\pyplotter\pyplotter\sources\main.py", line 347, in loadedDataFull
    self.addPlot(plotRef        = plotRef,
  File "\pyplotter\pyplotter\sources\main.py", line 482, in addPlot
    p = WidgetPlot1d(x                  = data[0],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\pyplotter\pyplotter\sources\widgetPlot1d.py", line 281, in __init__
    self.resize(*self.config['dialogWindowSize'])
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'float'
  resize(self, w: int, h: int): argument 1 has unexpected type 'float'
```

**Comment by edumur** [comment] 2023-07-25 13:07
Hi,

I am unable to reproduce that on my laptop.
Could you provide the following information:
 * PyQtGraph version: (output of pyqtgraph.__version__)
 * Qt Python binding: (output of pyqtgraph.Qt.VERSION_INFO)
 * Python version: 
 * NumPy version: (output of numpy.__version__)
 * Operating system: 
 * Installation method: (e.g. pip, conda, system packages, ...)

**Comment by Quantfoam** [comment] 2023-07-25 14:02
Hi,

Thanks for your answer:

Name: pyqtgraph
Version: 0.13.3

Qt Python binding: PyQt5 5.15.9 Qt 5.15.2

Python version: 3.11.0

Name: numpy
Version: 1.25.1

Windows 10

I have only pip installed (not conda) I followed the steps you describe on the main page (using GitHub) and it seemed the installation went fine.

Thanks for your help

**Comment by edumur** [comment] 2023-07-25 15:17
Thanks.

I was able to reproduce it locally.
I have pushed some fix on github.
Could you install the plotter from the github repo, test the fix on your machine and give me some feedback?

Thanks.

**Comment by Quantfoam** [comment] 2023-07-26 06:51
Works very well now. Thanks

I found another small problem. It seems the new BlueFors logs do not have the same date format. Also I have two screens and the app likes to jump from one to another when I select a db file. This is not a big deal.

 I get the following errors

`

QWindowsWindow::setGeometry: Unable to set geometry 6737x1377+0+23 (frame: 6753x1416-8-8) on QWidgetWindow/"MainWindowWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1377+0+23 (frame: 2576x1416-8-8) margins: 8, 31, 8, 8 min
imum size: 6737x352 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=6753,391 maxtrack=0,0)
QWindowsWindow::setGeometry: Unable to set geometry 6762x1377+0+23 (frame: 6778x1416-8-8) on QWidgetWindow/"MainWindowWindow" on "\\.\DISPLAY1". Resulting geometry: 2560x1377+0+23 (frame: 2576x1416-8-8) margins: 8, 31, 8, 8 min
imum size: 6762x352 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=6778,391 maxtrack=0,0)
Traceback (most recent call last):
  File "\pyplotter\pyplotter\sources\widgetBlueFors.py", line 113, in blueForsLoad
    x = pandasTimestamp2Int(pd.to_datetime(df['date']+'-'+df['time'], format=' %d-%m-%y-%H:%M:%S'))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 1050, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 453, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.venv\Lib\site-packages\pandas\core\tools\datetimes.py", line 484, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\tslibs\strptime.pyx", line 530, in pandas._libs.tslibs.strptime.array_strptime
  File "pandas\_libs\tslibs\strptime.pyx", line 351, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "25-07-23-00:00:42" doesn't match format " %d-%m-%y-%H:%M:%S", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

`

Thanks for your help

**Comment by edumur** [comment] 2023-07-26 08:22
Could you provide a BlueFors log file so that I can investigate?

**Comment by Quantfoam** [comment] 2023-07-26 09:36
Here it is, thanks

[23-07-25.zip](https://github.com/pyplotter/pyplotter/files/12170627/23-07-25.zip)

**Comment by edumur** [comment] 2023-07-26 12:34
Thanks.
It indeed appears that BlueFors changed the day format.

Should be ok now, please give me feedback.

**Comment by Quantfoam** [comment] 2023-07-26 13:03
Works great! Thanks

**Comment by edumur** [comment] 2023-07-26 13:07
Nice, I will update the pip package right away ;) .

**Comment by edumur** [comment] 2023-07-26 13:15
I am closing the issue then

**Closed as completed by edumur** 2023-07-26 13:15 UTC

**Comment by FalsePotato** [comment] 2024-04-19 14:01
Hello,

Trying to debug why simple CSVs aren't loading for me and tried loading the BlueFors db that was shared above (https://github.com/pyplotter/pyplotter/issues/2#issuecomment-1651372873_) to validate my setup is working with a known working db.

Installing from both PyPi and from the git repo yields same issue. 
Both under a conda environment on Windows 10 running Python 3.11.8
It looks like Pandas is unhappy with the dates now. (I believe my CSVs aren't parsing correctly as well due to str <-> float weirdness that seems to be the case here too).

`
(pyplotter) PS C:\git\pyplotter> python -m pyplotter.pyplotter
Traceback (most recent call last):
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\ops\array_ops.py", line 218, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\computation\expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\computation\expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: can only concatenate str (not "float") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\git\pyplotter\pyplotter\ui\widgetBlueFors.py", line 143, in blueForsLoad
    x = pandasTimestamp2Int(pd.to_datetime(df['date']+'-'+df['time'], format='%d-%m-%y-%H:%M:%S'))
                                           ~~~~~~~~~~~~~~^~~~~~~~~~~
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\arraylike.py", line 186, in __add__
    return self._arith_method(other, operator.add)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\series.py", line 6135, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\base.py", line 1382, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\ops\array_ops.py", line 283, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\ops\array_ops.py", line 227, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FalsePotato\miniconda3\envs\pyplotter\Lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only concatenate str (not "float") to str
`

My package versions: (pip list)
asteval                   0.9.32
asttokens                 2.4.1
attrs                     23.2.0
azure-core                1.30.1
azure-identity            1.16.0
broadbean                 0.14.0
cachetools                5.3.3
certifi                   2024.2.2
cf_xarray                 0.9.0
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
comm                      0.2.2
contextlib2               21.6.0
contourpy                 1.2.1
cryptography              42.0.5
cycler                    0.12.1
dask                      2024.4.1
debugpy                   1.8.1
decorator                 5.1.1
Deprecated                1.2.14
dill                      0.3.8
executing                 2.0.1
fonttools                 4.51.0
fsspec                    2024.3.1
future                    1.0.0
google-api-core           2.18.0
google-auth               2.29.0
googleapis-common-protos  1.63.0
h5netcdf                  1.3.0
h5py                      3.11.0
idna                      3.7
importlib-metadata        7.0.0
ipykernel                 6.29.4
ipython                   8.23.0
ipywidgets                8.1.2
jedi                      0.19.1
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_client            8.6.1
jupyter_core              5.7.2
jupyterlab_widgets        3.0.10
kiwisolver                1.4.5
lmfit                     1.3.0
locket                    1.0.0
matplotlib                3.8.4
matplotlib-inline         0.1.7
msal                      1.28.0
msal-extensions           1.1.0
multiprocess              0.70.16
nest-asyncio              1.6.0
numpy                     1.26.4
opencensus                0.11.4
opencensus-context        0.1.3
opencensus-ext-azure      1.1.13
opentelemetry-api         1.24.0
packaging                 23.2
pandas                    2.2.2
parso                     0.8.4
partd                     1.4.1
pillow                    10.3.0
pip                       23.3.1
platformdirs              4.2.0
portalocker               2.8.2
prompt-toolkit            3.0.43
proto-plus                1.23.0
protobuf                  4.25.3
psutil                    5.9.8
pure-eval                 0.2.2
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycparser                 2.22
Pygments                  2.17.2
PyJWT                     2.8.0
PyOpenGL                  3.1.7
pyparsing                 3.1.2
pyplotter                 0.3.7
PyQt5                     5.15.10
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.13.0
pyqtgraph                 0.13.4
PyQtWebEngine             5.15.6
PyQtWebEngine-Qt5         5.15.2
python-dateutil           2.9.0.post0
pytz                      2024.1
PyVISA                    1.14.1
pywin32                   306
PyYAML                    6.0.1
pyzmq                     26.0.1
qcodes                    0.44.1
QDarkStyle                3.2.3
QtPy                      2.4.1
referencing               0.34.0
requests                  2.31.0
rpds-py                   0.18.0
rsa                       4.9
ruamel.yaml               0.18.6
ruamel.yaml.clib          0.2.8
schema                    0.7.5
scikit-rf                 0.32.0
scipy                     1.13.0
setuptools                68.2.2
six                       1.16.0
stack-data                0.6.3
tabulate                  0.9.0
toolz                     0.12.1
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.3
typing_extensions         4.11.0
tzdata                    2024.1
uncertainties             3.1.7
urllib3                   2.2.1
versioningit              3.1.0
wcwidth                   0.2.13
websockets                12.0
wheel                     0.41.2
widgetsnbextension        4.0.10
wrapt                     1.16.0
xarray                    2024.3.0
zipp                      3.18.1
